// CART

export const FILL_CART = "FILL_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const EMPTY_CART = "EMPTY_CART";
export const UPDATE_QUANTITY = "UPDATE_QUANTITY";
export const REFRESH_CART = "REFRESH_CART";

// Products

export const GET_PRODUCTS = "GET_PRODUCTS";
export const FILTER_RANGE_PRODUCTS = "RANGE_FILTER_PRODUCTS";

// Checkout

export const GENERATE_CHECKOUT_TOKEN = "GENERATE_CHECKOUT_TOKEN";
export const UPDATE_SHIPPING_CHECKOUT = "SHIPPING_DATA_CHECKOUT";
export const NEXT_CHECKOUT_STEP = "NEXT_CHECKOUT_STEP";
export const BACK_CHECKOUT_STEP = "BACK_CHECKOUT_STEP";
export const CAPTURE_CHECKOUT = "CAPTURE_CHECKOUT";
export const INITIAL_CHECKOUT_STEP = "INITIAL_CHECKOUT_STEP";
